In [1]:
import torch
torch.__version__

'1.11.0+cu113'

## Autograd

通过设置 requires_grad 标识为Ture来告诉Pytorch需要对该张量进行自动求导

In [3]:
_ = torch.rand(3, 3, requires_grad=True)
_

tensor([[0.9614, 0.3022, 0.5287],
        [0.7502, 0.6732, 0.9621],
        [0.2449, 0.9077, 0.9530]], requires_grad=True)

只有浮点类型才支持求梯度

In [10]:
x = torch.arange(1,10).view(3,3).float()
x.requires_grad = True
x,x.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]], requires_grad=True),
 torch.Size([3, 3]))

In [12]:
y = torch.arange(1,19,2).view(3,3).float()
y.requires_grad = True
y,y.shape

(tensor([[ 1.,  3.,  5.],
         [ 7.,  9., 11.],
         [13., 15., 17.]], requires_grad=True),
 torch.Size([3, 3]))

In [13]:
z= x**2+y**3
z

tensor([[2.0000e+00, 3.1000e+01, 1.3400e+02],
        [3.5900e+02, 7.5400e+02, 1.3670e+03],
        [2.2460e+03, 3.4390e+03, 4.9940e+03]], grad_fn=<AddBackward0>)

z.backward()：
* 若z是标量可以直接用
* 若z是Tensor，那么需要输入一个大小相同的张量

In [14]:
#返回值不是一个标量，所以需要输入一个大小相同的张量作为参数，这里我们用ones_like函数根据x生成一个张量
z.backward(torch.ones_like(x))
print(x.grad)
# 由于y和x的形状一样
print(y.grad)

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.],
        [14., 16., 18.]])
tensor([[  3.,  27.,  75.],
        [147., 243., 363.],
        [507., 675., 867.]])


3 * y<sup>2</sup>

In [15]:
3*y**2

tensor([[  3.,  27.,  75.],
        [147., 243., 363.],
        [507., 675., 867.]], grad_fn=<MulBackward0>)